# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/j_banaszewski/git/MTF/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/j_banaszewski/git/MTF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j_banaszewski/git/MTF/CMakeFiles /home/j_banaszewski/git/MTF/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j_banaszewski/git/MTF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MTF

# Build rule for target.
MTF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MTF
.PHONY : MTF

# fast build rule for target.
MTF/fast:
	$(MAKE) -f CMakeFiles/MTF.dir/build.make CMakeFiles/MTF.dir/build
.PHONY : MTF/fast

#=============================================================================
# Target rules for targets named MTF_GTEST

# Build rule for target.
MTF_GTEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MTF_GTEST
.PHONY : MTF_GTEST

# fast build rule for target.
MTF_GTEST/fast:
	$(MAKE) -f CMakeFiles/MTF_GTEST.dir/build.make CMakeFiles/MTF_GTEST.dir/build
.PHONY : MTF_GTEST/fast

#=============================================================================
# Target rules for targets named MTF_TEST

# Build rule for target.
MTF_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MTF_TEST
.PHONY : MTF_TEST

# fast build rule for target.
MTF_TEST/fast:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/build
.PHONY : MTF_TEST/fast

#=============================================================================
# Target rules for targets named algorithm

# Build rule for target.
algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algorithm
.PHONY : algorithm

# fast build rule for target.
algorithm/fast:
	$(MAKE) -f algorithms/CMakeFiles/algorithm.dir/build.make algorithms/CMakeFiles/algorithm.dir/build
.PHONY : algorithm/fast

#=============================================================================
# Target rules for targets named configuration

# Build rule for target.
configuration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 configuration
.PHONY : configuration

# fast build rule for target.
configuration/fast:
	$(MAKE) -f controller/CMakeFiles/configuration.dir/build.make controller/CMakeFiles/configuration.dir/build
.PHONY : configuration/fast

#=============================================================================
# Target rules for targets named data_managment

# Build rule for target.
data_managment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data_managment
.PHONY : data_managment

# fast build rule for target.
data_managment/fast:
	$(MAKE) -f data_managment/CMakeFiles/data_managment.dir/build.make data_managment/CMakeFiles/data_managment.dir/build
.PHONY : data_managment/fast

#=============================================================================
# Target rules for targets named event

# Build rule for target.
event: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 event
.PHONY : event

# fast build rule for target.
event/fast:
	$(MAKE) -f events/CMakeFiles/event.dir/build.make events/CMakeFiles/event.dir/build
.PHONY : event/fast

#=============================================================================
# Target rules for targets named exception

# Build rule for target.
exception: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exception
.PHONY : exception

# fast build rule for target.
exception/fast:
	$(MAKE) -f exceptions/CMakeFiles/exception.dir/build.make exceptions/CMakeFiles/exception.dir/build
.PHONY : exception/fast

#=============================================================================
# Target rules for targets named element

# Build rule for target.
element: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 element
.PHONY : element

# fast build rule for target.
element/fast:
	$(MAKE) -f elements/CMakeFiles/element.dir/build.make elements/CMakeFiles/element.dir/build
.PHONY : element/fast

#=============================================================================
# Target rules for targets named result

# Build rule for target.
result: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 result
.PHONY : result

# fast build rule for target.
result/fast:
	$(MAKE) -f results/CMakeFiles/result.dir/build.make results/CMakeFiles/result.dir/build
.PHONY : result/fast

#=============================================================================
# Target rules for targets named tool

# Build rule for target.
tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tool
.PHONY : tool

# fast build rule for target.
tool/fast:
	$(MAKE) -f tools/CMakeFiles/tool.dir/build.make tools/CMakeFiles/tool.dir/build
.PHONY : tool/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f utils/CMakeFiles/util.dir/build.make utils/CMakeFiles/util.dir/build
.PHONY : util/fast

CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

algorithms/algorithm_container.o: algorithms/algorithm_container.cpp.o
.PHONY : algorithms/algorithm_container.o

# target to build an object file
algorithms/algorithm_container.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/algorithm_container.cpp.o
.PHONY : algorithms/algorithm_container.cpp.o

algorithms/algorithm_container.i: algorithms/algorithm_container.cpp.i
.PHONY : algorithms/algorithm_container.i

# target to preprocess a source file
algorithms/algorithm_container.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/algorithm_container.cpp.i
.PHONY : algorithms/algorithm_container.cpp.i

algorithms/algorithm_container.s: algorithms/algorithm_container.cpp.s
.PHONY : algorithms/algorithm_container.s

# target to generate assembly for a file
algorithms/algorithm_container.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/algorithm_container.cpp.s
.PHONY : algorithms/algorithm_container.cpp.s

algorithms/matrix/mtf_matrix.o: algorithms/matrix/mtf_matrix.cpp.o
.PHONY : algorithms/matrix/mtf_matrix.o

# target to build an object file
algorithms/matrix/mtf_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/matrix/mtf_matrix.cpp.o
.PHONY : algorithms/matrix/mtf_matrix.cpp.o

algorithms/matrix/mtf_matrix.i: algorithms/matrix/mtf_matrix.cpp.i
.PHONY : algorithms/matrix/mtf_matrix.i

# target to preprocess a source file
algorithms/matrix/mtf_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/matrix/mtf_matrix.cpp.i
.PHONY : algorithms/matrix/mtf_matrix.cpp.i

algorithms/matrix/mtf_matrix.s: algorithms/matrix/mtf_matrix.cpp.s
.PHONY : algorithms/matrix/mtf_matrix.s

# target to generate assembly for a file
algorithms/matrix/mtf_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/matrix/mtf_matrix.cpp.s
.PHONY : algorithms/matrix/mtf_matrix.cpp.s

algorithms/move_to_front/move_to_front.o: algorithms/move_to_front/move_to_front.cpp.o
.PHONY : algorithms/move_to_front/move_to_front.o

# target to build an object file
algorithms/move_to_front/move_to_front.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/move_to_front/move_to_front.cpp.o
.PHONY : algorithms/move_to_front/move_to_front.cpp.o

algorithms/move_to_front/move_to_front.i: algorithms/move_to_front/move_to_front.cpp.i
.PHONY : algorithms/move_to_front/move_to_front.i

# target to preprocess a source file
algorithms/move_to_front/move_to_front.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/move_to_front/move_to_front.cpp.i
.PHONY : algorithms/move_to_front/move_to_front.cpp.i

algorithms/move_to_front/move_to_front.s: algorithms/move_to_front/move_to_front.cpp.s
.PHONY : algorithms/move_to_front/move_to_front.s

# target to generate assembly for a file
algorithms/move_to_front/move_to_front.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/move_to_front/move_to_front.cpp.s
.PHONY : algorithms/move_to_front/move_to_front.cpp.s

algorithms/tree/random_tree_root.o: algorithms/tree/random_tree_root.cpp.o
.PHONY : algorithms/tree/random_tree_root.o

# target to build an object file
algorithms/tree/random_tree_root.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/tree/random_tree_root.cpp.o
.PHONY : algorithms/tree/random_tree_root.cpp.o

algorithms/tree/random_tree_root.i: algorithms/tree/random_tree_root.cpp.i
.PHONY : algorithms/tree/random_tree_root.i

# target to preprocess a source file
algorithms/tree/random_tree_root.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/tree/random_tree_root.cpp.i
.PHONY : algorithms/tree/random_tree_root.cpp.i

algorithms/tree/random_tree_root.s: algorithms/tree/random_tree_root.cpp.s
.PHONY : algorithms/tree/random_tree_root.s

# target to generate assembly for a file
algorithms/tree/random_tree_root.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/tree/random_tree_root.cpp.s
.PHONY : algorithms/tree/random_tree_root.cpp.s

algorithms/tree/tree_root.o: algorithms/tree/tree_root.cpp.o
.PHONY : algorithms/tree/tree_root.o

# target to build an object file
algorithms/tree/tree_root.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/tree/tree_root.cpp.o
.PHONY : algorithms/tree/tree_root.cpp.o

algorithms/tree/tree_root.i: algorithms/tree/tree_root.cpp.i
.PHONY : algorithms/tree/tree_root.i

# target to preprocess a source file
algorithms/tree/tree_root.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/tree/tree_root.cpp.i
.PHONY : algorithms/tree/tree_root.cpp.i

algorithms/tree/tree_root.s: algorithms/tree/tree_root.cpp.s
.PHONY : algorithms/tree/tree_root.s

# target to generate assembly for a file
algorithms/tree/tree_root.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/algorithms/tree/tree_root.cpp.s
.PHONY : algorithms/tree/tree_root.cpp.s

controller/analysis_runner.o: controller/analysis_runner.cpp.o
.PHONY : controller/analysis_runner.o

# target to build an object file
controller/analysis_runner.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/analysis_runner.cpp.o
.PHONY : controller/analysis_runner.cpp.o

controller/analysis_runner.i: controller/analysis_runner.cpp.i
.PHONY : controller/analysis_runner.i

# target to preprocess a source file
controller/analysis_runner.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/analysis_runner.cpp.i
.PHONY : controller/analysis_runner.cpp.i

controller/analysis_runner.s: controller/analysis_runner.cpp.s
.PHONY : controller/analysis_runner.s

# target to generate assembly for a file
controller/analysis_runner.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/analysis_runner.cpp.s
.PHONY : controller/analysis_runner.cpp.s

controller/configuration/configuration.o: controller/configuration/configuration.cpp.o
.PHONY : controller/configuration/configuration.o

# target to build an object file
controller/configuration/configuration.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/configuration/configuration.cpp.o
.PHONY : controller/configuration/configuration.cpp.o

controller/configuration/configuration.i: controller/configuration/configuration.cpp.i
.PHONY : controller/configuration/configuration.i

# target to preprocess a source file
controller/configuration/configuration.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/configuration/configuration.cpp.i
.PHONY : controller/configuration/configuration.cpp.i

controller/configuration/configuration.s: controller/configuration/configuration.cpp.s
.PHONY : controller/configuration/configuration.s

# target to generate assembly for a file
controller/configuration/configuration.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/configuration/configuration.cpp.s
.PHONY : controller/configuration/configuration.cpp.s

controller/configuration/objects_builder.o: controller/configuration/objects_builder.cpp.o
.PHONY : controller/configuration/objects_builder.o

# target to build an object file
controller/configuration/objects_builder.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/configuration/objects_builder.cpp.o
.PHONY : controller/configuration/objects_builder.cpp.o

controller/configuration/objects_builder.i: controller/configuration/objects_builder.cpp.i
.PHONY : controller/configuration/objects_builder.i

# target to preprocess a source file
controller/configuration/objects_builder.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/configuration/objects_builder.cpp.i
.PHONY : controller/configuration/objects_builder.cpp.i

controller/configuration/objects_builder.s: controller/configuration/objects_builder.cpp.s
.PHONY : controller/configuration/objects_builder.s

# target to generate assembly for a file
controller/configuration/objects_builder.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/controller/configuration/objects_builder.cpp.s
.PHONY : controller/configuration/objects_builder.cpp.s

data_managment/data_output/csv_data_output.o: data_managment/data_output/csv_data_output.cpp.o
.PHONY : data_managment/data_output/csv_data_output.o

# target to build an object file
data_managment/data_output/csv_data_output.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/csv_data_output.cpp.o
.PHONY : data_managment/data_output/csv_data_output.cpp.o

data_managment/data_output/csv_data_output.i: data_managment/data_output/csv_data_output.cpp.i
.PHONY : data_managment/data_output/csv_data_output.i

# target to preprocess a source file
data_managment/data_output/csv_data_output.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/csv_data_output.cpp.i
.PHONY : data_managment/data_output/csv_data_output.cpp.i

data_managment/data_output/csv_data_output.s: data_managment/data_output/csv_data_output.cpp.s
.PHONY : data_managment/data_output/csv_data_output.s

# target to generate assembly for a file
data_managment/data_output/csv_data_output.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/csv_data_output.cpp.s
.PHONY : data_managment/data_output/csv_data_output.cpp.s

data_managment/data_output/csv_file_data_output.o: data_managment/data_output/csv_file_data_output.cpp.o
.PHONY : data_managment/data_output/csv_file_data_output.o

# target to build an object file
data_managment/data_output/csv_file_data_output.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/csv_file_data_output.cpp.o
.PHONY : data_managment/data_output/csv_file_data_output.cpp.o

data_managment/data_output/csv_file_data_output.i: data_managment/data_output/csv_file_data_output.cpp.i
.PHONY : data_managment/data_output/csv_file_data_output.i

# target to preprocess a source file
data_managment/data_output/csv_file_data_output.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/csv_file_data_output.cpp.i
.PHONY : data_managment/data_output/csv_file_data_output.cpp.i

data_managment/data_output/csv_file_data_output.s: data_managment/data_output/csv_file_data_output.cpp.s
.PHONY : data_managment/data_output/csv_file_data_output.s

# target to generate assembly for a file
data_managment/data_output/csv_file_data_output.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/csv_file_data_output.cpp.s
.PHONY : data_managment/data_output/csv_file_data_output.cpp.s

data_managment/data_output/file_data_output.o: data_managment/data_output/file_data_output.cpp.o
.PHONY : data_managment/data_output/file_data_output.o

# target to build an object file
data_managment/data_output/file_data_output.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/file_data_output.cpp.o
.PHONY : data_managment/data_output/file_data_output.cpp.o

data_managment/data_output/file_data_output.i: data_managment/data_output/file_data_output.cpp.i
.PHONY : data_managment/data_output/file_data_output.i

# target to preprocess a source file
data_managment/data_output/file_data_output.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/file_data_output.cpp.i
.PHONY : data_managment/data_output/file_data_output.cpp.i

data_managment/data_output/file_data_output.s: data_managment/data_output/file_data_output.cpp.s
.PHONY : data_managment/data_output/file_data_output.s

# target to generate assembly for a file
data_managment/data_output/file_data_output.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_output/file_data_output.cpp.s
.PHONY : data_managment/data_output/file_data_output.cpp.s

data_managment/data_provider/file_data_provider.o: data_managment/data_provider/file_data_provider.cpp.o
.PHONY : data_managment/data_provider/file_data_provider.o

# target to build an object file
data_managment/data_provider/file_data_provider.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_provider/file_data_provider.cpp.o
.PHONY : data_managment/data_provider/file_data_provider.cpp.o

data_managment/data_provider/file_data_provider.i: data_managment/data_provider/file_data_provider.cpp.i
.PHONY : data_managment/data_provider/file_data_provider.i

# target to preprocess a source file
data_managment/data_provider/file_data_provider.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_provider/file_data_provider.cpp.i
.PHONY : data_managment/data_provider/file_data_provider.cpp.i

data_managment/data_provider/file_data_provider.s: data_managment/data_provider/file_data_provider.cpp.s
.PHONY : data_managment/data_provider/file_data_provider.s

# target to generate assembly for a file
data_managment/data_provider/file_data_provider.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/data_provider/file_data_provider.cpp.s
.PHONY : data_managment/data_provider/file_data_provider.cpp.s

data_managment/database.o: data_managment/database.cpp.o
.PHONY : data_managment/database.o

# target to build an object file
data_managment/database.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/database.cpp.o
.PHONY : data_managment/database.cpp.o

data_managment/database.i: data_managment/database.cpp.i
.PHONY : data_managment/database.i

# target to preprocess a source file
data_managment/database.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/database.cpp.i
.PHONY : data_managment/database.cpp.i

data_managment/database.s: data_managment/database.cpp.s
.PHONY : data_managment/database.s

# target to generate assembly for a file
data_managment/database.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/database.cpp.s
.PHONY : data_managment/database.cpp.s

data_managment/results_collectors/data_collector.o: data_managment/results_collectors/data_collector.cpp.o
.PHONY : data_managment/results_collectors/data_collector.o

# target to build an object file
data_managment/results_collectors/data_collector.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/data_collector.cpp.o
.PHONY : data_managment/results_collectors/data_collector.cpp.o

data_managment/results_collectors/data_collector.i: data_managment/results_collectors/data_collector.cpp.i
.PHONY : data_managment/results_collectors/data_collector.i

# target to preprocess a source file
data_managment/results_collectors/data_collector.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/data_collector.cpp.i
.PHONY : data_managment/results_collectors/data_collector.cpp.i

data_managment/results_collectors/data_collector.s: data_managment/results_collectors/data_collector.cpp.s
.PHONY : data_managment/results_collectors/data_collector.s

# target to generate assembly for a file
data_managment/results_collectors/data_collector.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/data_collector.cpp.s
.PHONY : data_managment/results_collectors/data_collector.cpp.s

data_managment/results_collectors/judge_collector.o: data_managment/results_collectors/judge_collector.cpp.o
.PHONY : data_managment/results_collectors/judge_collector.o

# target to build an object file
data_managment/results_collectors/judge_collector.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/judge_collector.cpp.o
.PHONY : data_managment/results_collectors/judge_collector.cpp.o

data_managment/results_collectors/judge_collector.i: data_managment/results_collectors/judge_collector.cpp.i
.PHONY : data_managment/results_collectors/judge_collector.i

# target to preprocess a source file
data_managment/results_collectors/judge_collector.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/judge_collector.cpp.i
.PHONY : data_managment/results_collectors/judge_collector.cpp.i

data_managment/results_collectors/judge_collector.s: data_managment/results_collectors/judge_collector.cpp.s
.PHONY : data_managment/results_collectors/judge_collector.s

# target to generate assembly for a file
data_managment/results_collectors/judge_collector.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/judge_collector.cpp.s
.PHONY : data_managment/results_collectors/judge_collector.cpp.s

data_managment/results_collectors/result_collector.o: data_managment/results_collectors/result_collector.cpp.o
.PHONY : data_managment/results_collectors/result_collector.o

# target to build an object file
data_managment/results_collectors/result_collector.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/result_collector.cpp.o
.PHONY : data_managment/results_collectors/result_collector.cpp.o

data_managment/results_collectors/result_collector.i: data_managment/results_collectors/result_collector.cpp.i
.PHONY : data_managment/results_collectors/result_collector.i

# target to preprocess a source file
data_managment/results_collectors/result_collector.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/result_collector.cpp.i
.PHONY : data_managment/results_collectors/result_collector.cpp.i

data_managment/results_collectors/result_collector.s: data_managment/results_collectors/result_collector.cpp.s
.PHONY : data_managment/results_collectors/result_collector.s

# target to generate assembly for a file
data_managment/results_collectors/result_collector.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/data_managment/results_collectors/result_collector.cpp.s
.PHONY : data_managment/results_collectors/result_collector.cpp.s

elements/complex_difference_element.o: elements/complex_difference_element.cpp.o
.PHONY : elements/complex_difference_element.o

# target to build an object file
elements/complex_difference_element.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/complex_difference_element.cpp.o
.PHONY : elements/complex_difference_element.cpp.o

elements/complex_difference_element.i: elements/complex_difference_element.cpp.i
.PHONY : elements/complex_difference_element.i

# target to preprocess a source file
elements/complex_difference_element.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/complex_difference_element.cpp.i
.PHONY : elements/complex_difference_element.cpp.i

elements/complex_difference_element.s: elements/complex_difference_element.cpp.s
.PHONY : elements/complex_difference_element.s

# target to generate assembly for a file
elements/complex_difference_element.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/complex_difference_element.cpp.s
.PHONY : elements/complex_difference_element.cpp.s

elements/element.o: elements/element.cpp.o
.PHONY : elements/element.o

# target to build an object file
elements/element.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/element.cpp.o
.PHONY : elements/element.cpp.o

elements/element.i: elements/element.cpp.i
.PHONY : elements/element.i

# target to preprocess a source file
elements/element.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/element.cpp.i
.PHONY : elements/element.cpp.i

elements/element.s: elements/element.cpp.s
.PHONY : elements/element.s

# target to generate assembly for a file
elements/element.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/element.cpp.s
.PHONY : elements/element.cpp.s

elements/simple_element.o: elements/simple_element.cpp.o
.PHONY : elements/simple_element.o

# target to build an object file
elements/simple_element.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/simple_element.cpp.o
.PHONY : elements/simple_element.cpp.o

elements/simple_element.i: elements/simple_element.cpp.i
.PHONY : elements/simple_element.i

# target to preprocess a source file
elements/simple_element.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/simple_element.cpp.i
.PHONY : elements/simple_element.cpp.i

elements/simple_element.s: elements/simple_element.cpp.s
.PHONY : elements/simple_element.s

# target to generate assembly for a file
elements/simple_element.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/elements/simple_element.cpp.s
.PHONY : elements/simple_element.cpp.s

events/event_notifier.o: events/event_notifier.cpp.o
.PHONY : events/event_notifier.o

# target to build an object file
events/event_notifier.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/events/event_notifier.cpp.o
.PHONY : events/event_notifier.cpp.o

events/event_notifier.i: events/event_notifier.cpp.i
.PHONY : events/event_notifier.i

# target to preprocess a source file
events/event_notifier.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/events/event_notifier.cpp.i
.PHONY : events/event_notifier.cpp.i

events/event_notifier.s: events/event_notifier.cpp.s
.PHONY : events/event_notifier.s

# target to generate assembly for a file
events/event_notifier.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/events/event_notifier.cpp.s
.PHONY : events/event_notifier.cpp.s

exceptions/data_provider_exception.o: exceptions/data_provider_exception.cpp.o
.PHONY : exceptions/data_provider_exception.o

# target to build an object file
exceptions/data_provider_exception.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/data_provider_exception.cpp.o
.PHONY : exceptions/data_provider_exception.cpp.o

exceptions/data_provider_exception.i: exceptions/data_provider_exception.cpp.i
.PHONY : exceptions/data_provider_exception.i

# target to preprocess a source file
exceptions/data_provider_exception.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/data_provider_exception.cpp.i
.PHONY : exceptions/data_provider_exception.cpp.i

exceptions/data_provider_exception.s: exceptions/data_provider_exception.cpp.s
.PHONY : exceptions/data_provider_exception.s

# target to generate assembly for a file
exceptions/data_provider_exception.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/data_provider_exception.cpp.s
.PHONY : exceptions/data_provider_exception.cpp.s

exceptions/database_exception.o: exceptions/database_exception.cpp.o
.PHONY : exceptions/database_exception.o

# target to build an object file
exceptions/database_exception.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/database_exception.cpp.o
.PHONY : exceptions/database_exception.cpp.o

exceptions/database_exception.i: exceptions/database_exception.cpp.i
.PHONY : exceptions/database_exception.i

# target to preprocess a source file
exceptions/database_exception.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/database_exception.cpp.i
.PHONY : exceptions/database_exception.cpp.i

exceptions/database_exception.s: exceptions/database_exception.cpp.s
.PHONY : exceptions/database_exception.s

# target to generate assembly for a file
exceptions/database_exception.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/database_exception.cpp.s
.PHONY : exceptions/database_exception.cpp.s

exceptions/element_already_exists.o: exceptions/element_already_exists.cpp.o
.PHONY : exceptions/element_already_exists.o

# target to build an object file
exceptions/element_already_exists.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/element_already_exists.cpp.o
.PHONY : exceptions/element_already_exists.cpp.o

exceptions/element_already_exists.i: exceptions/element_already_exists.cpp.i
.PHONY : exceptions/element_already_exists.i

# target to preprocess a source file
exceptions/element_already_exists.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/element_already_exists.cpp.i
.PHONY : exceptions/element_already_exists.cpp.i

exceptions/element_already_exists.s: exceptions/element_already_exists.cpp.s
.PHONY : exceptions/element_already_exists.s

# target to generate assembly for a file
exceptions/element_already_exists.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/element_already_exists.cpp.s
.PHONY : exceptions/element_already_exists.cpp.s

exceptions/end_of_file_exception.o: exceptions/end_of_file_exception.cpp.o
.PHONY : exceptions/end_of_file_exception.o

# target to build an object file
exceptions/end_of_file_exception.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/end_of_file_exception.cpp.o
.PHONY : exceptions/end_of_file_exception.cpp.o

exceptions/end_of_file_exception.i: exceptions/end_of_file_exception.cpp.i
.PHONY : exceptions/end_of_file_exception.i

# target to preprocess a source file
exceptions/end_of_file_exception.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/end_of_file_exception.cpp.i
.PHONY : exceptions/end_of_file_exception.cpp.i

exceptions/end_of_file_exception.s: exceptions/end_of_file_exception.cpp.s
.PHONY : exceptions/end_of_file_exception.s

# target to generate assembly for a file
exceptions/end_of_file_exception.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/end_of_file_exception.cpp.s
.PHONY : exceptions/end_of_file_exception.cpp.s

exceptions/file_path_exception.o: exceptions/file_path_exception.cpp.o
.PHONY : exceptions/file_path_exception.o

# target to build an object file
exceptions/file_path_exception.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/file_path_exception.cpp.o
.PHONY : exceptions/file_path_exception.cpp.o

exceptions/file_path_exception.i: exceptions/file_path_exception.cpp.i
.PHONY : exceptions/file_path_exception.i

# target to preprocess a source file
exceptions/file_path_exception.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/file_path_exception.cpp.i
.PHONY : exceptions/file_path_exception.cpp.i

exceptions/file_path_exception.s: exceptions/file_path_exception.cpp.s
.PHONY : exceptions/file_path_exception.s

# target to generate assembly for a file
exceptions/file_path_exception.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/file_path_exception.cpp.s
.PHONY : exceptions/file_path_exception.cpp.s

exceptions/invalid_index_exception.o: exceptions/invalid_index_exception.cpp.o
.PHONY : exceptions/invalid_index_exception.o

# target to build an object file
exceptions/invalid_index_exception.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/invalid_index_exception.cpp.o
.PHONY : exceptions/invalid_index_exception.cpp.o

exceptions/invalid_index_exception.i: exceptions/invalid_index_exception.cpp.i
.PHONY : exceptions/invalid_index_exception.i

# target to preprocess a source file
exceptions/invalid_index_exception.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/invalid_index_exception.cpp.i
.PHONY : exceptions/invalid_index_exception.cpp.i

exceptions/invalid_index_exception.s: exceptions/invalid_index_exception.cpp.s
.PHONY : exceptions/invalid_index_exception.s

# target to generate assembly for a file
exceptions/invalid_index_exception.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/invalid_index_exception.cpp.s
.PHONY : exceptions/invalid_index_exception.cpp.s

exceptions/invalid_name_exception.o: exceptions/invalid_name_exception.cpp.o
.PHONY : exceptions/invalid_name_exception.o

# target to build an object file
exceptions/invalid_name_exception.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/invalid_name_exception.cpp.o
.PHONY : exceptions/invalid_name_exception.cpp.o

exceptions/invalid_name_exception.i: exceptions/invalid_name_exception.cpp.i
.PHONY : exceptions/invalid_name_exception.i

# target to preprocess a source file
exceptions/invalid_name_exception.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/invalid_name_exception.cpp.i
.PHONY : exceptions/invalid_name_exception.cpp.i

exceptions/invalid_name_exception.s: exceptions/invalid_name_exception.cpp.s
.PHONY : exceptions/invalid_name_exception.s

# target to generate assembly for a file
exceptions/invalid_name_exception.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/invalid_name_exception.cpp.s
.PHONY : exceptions/invalid_name_exception.cpp.s

exceptions/non_existing_element.o: exceptions/non_existing_element.cpp.o
.PHONY : exceptions/non_existing_element.o

# target to build an object file
exceptions/non_existing_element.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/non_existing_element.cpp.o
.PHONY : exceptions/non_existing_element.cpp.o

exceptions/non_existing_element.i: exceptions/non_existing_element.cpp.i
.PHONY : exceptions/non_existing_element.i

# target to preprocess a source file
exceptions/non_existing_element.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/non_existing_element.cpp.i
.PHONY : exceptions/non_existing_element.cpp.i

exceptions/non_existing_element.s: exceptions/non_existing_element.cpp.s
.PHONY : exceptions/non_existing_element.s

# target to generate assembly for a file
exceptions/non_existing_element.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/exceptions/non_existing_element.cpp.s
.PHONY : exceptions/non_existing_element.cpp.s

gtest/analysis_runner_test.o: gtest/analysis_runner_test.cpp.o
.PHONY : gtest/analysis_runner_test.o

# target to build an object file
gtest/analysis_runner_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/gtest/analysis_runner_test.cpp.o
.PHONY : gtest/analysis_runner_test.cpp.o

gtest/analysis_runner_test.i: gtest/analysis_runner_test.cpp.i
.PHONY : gtest/analysis_runner_test.i

# target to preprocess a source file
gtest/analysis_runner_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/gtest/analysis_runner_test.cpp.i
.PHONY : gtest/analysis_runner_test.cpp.i

gtest/analysis_runner_test.s: gtest/analysis_runner_test.cpp.s
.PHONY : gtest/analysis_runner_test.s

# target to generate assembly for a file
gtest/analysis_runner_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/gtest/analysis_runner_test.cpp.s
.PHONY : gtest/analysis_runner_test.cpp.s

gtest/gtest_main.o: gtest/gtest_main.cpp.o
.PHONY : gtest/gtest_main.o

# target to build an object file
gtest/gtest_main.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_GTEST.dir/build.make CMakeFiles/MTF_GTEST.dir/gtest/gtest_main.cpp.o
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/gtest/gtest_main.cpp.o
.PHONY : gtest/gtest_main.cpp.o

gtest/gtest_main.i: gtest/gtest_main.cpp.i
.PHONY : gtest/gtest_main.i

# target to preprocess a source file
gtest/gtest_main.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_GTEST.dir/build.make CMakeFiles/MTF_GTEST.dir/gtest/gtest_main.cpp.i
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/gtest/gtest_main.cpp.i
.PHONY : gtest/gtest_main.cpp.i

gtest/gtest_main.s: gtest/gtest_main.cpp.s
.PHONY : gtest/gtest_main.s

# target to generate assembly for a file
gtest/gtest_main.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_GTEST.dir/build.make CMakeFiles/MTF_GTEST.dir/gtest/gtest_main.cpp.s
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/gtest/gtest_main.cpp.s
.PHONY : gtest/gtest_main.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/MTF.dir/build.make CMakeFiles/MTF.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/MTF.dir/build.make CMakeFiles/MTF.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/MTF.dir/build.make CMakeFiles/MTF.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/main.cpp.s
.PHONY : main.cpp.s

main_test.o: main_test.cpp.o
.PHONY : main_test.o

# target to build an object file
main_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/main_test.cpp.o
.PHONY : main_test.cpp.o

main_test.i: main_test.cpp.i
.PHONY : main_test.i

# target to preprocess a source file
main_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/main_test.cpp.i
.PHONY : main_test.cpp.i

main_test.s: main_test.cpp.s
.PHONY : main_test.s

# target to generate assembly for a file
main_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/main_test.cpp.s
.PHONY : main_test.cpp.s

results/overall_result.o: results/overall_result.cpp.o
.PHONY : results/overall_result.o

# target to build an object file
results/overall_result.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/results/overall_result.cpp.o
.PHONY : results/overall_result.cpp.o

results/overall_result.i: results/overall_result.cpp.i
.PHONY : results/overall_result.i

# target to preprocess a source file
results/overall_result.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/results/overall_result.cpp.i
.PHONY : results/overall_result.cpp.i

results/overall_result.s: results/overall_result.cpp.s
.PHONY : results/overall_result.s

# target to generate assembly for a file
results/overall_result.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/results/overall_result.cpp.s
.PHONY : results/overall_result.cpp.s

results/result.o: results/result.cpp.o
.PHONY : results/result.o

# target to build an object file
results/result.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/results/result.cpp.o
.PHONY : results/result.cpp.o

results/result.i: results/result.cpp.i
.PHONY : results/result.i

# target to preprocess a source file
results/result.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/results/result.cpp.i
.PHONY : results/result.cpp.i

results/result.s: results/result.cpp.s
.PHONY : results/result.s

# target to generate assembly for a file
results/result.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/results/result.cpp.s
.PHONY : results/result.cpp.s

test/data_collector_test.o: test/data_collector_test.cpp.o
.PHONY : test/data_collector_test.o

# target to build an object file
test/data_collector_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/data_collector_test.cpp.o
.PHONY : test/data_collector_test.cpp.o

test/data_collector_test.i: test/data_collector_test.cpp.i
.PHONY : test/data_collector_test.i

# target to preprocess a source file
test/data_collector_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/data_collector_test.cpp.i
.PHONY : test/data_collector_test.cpp.i

test/data_collector_test.s: test/data_collector_test.cpp.s
.PHONY : test/data_collector_test.s

# target to generate assembly for a file
test/data_collector_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/data_collector_test.cpp.s
.PHONY : test/data_collector_test.cpp.s

test/database_test.o: test/database_test.cpp.o
.PHONY : test/database_test.o

# target to build an object file
test/database_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/database_test.cpp.o
.PHONY : test/database_test.cpp.o

test/database_test.i: test/database_test.cpp.i
.PHONY : test/database_test.i

# target to preprocess a source file
test/database_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/database_test.cpp.i
.PHONY : test/database_test.cpp.i

test/database_test.s: test/database_test.cpp.s
.PHONY : test/database_test.s

# target to generate assembly for a file
test/database_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/database_test.cpp.s
.PHONY : test/database_test.cpp.s

test/element_test.o: test/element_test.cpp.o
.PHONY : test/element_test.o

# target to build an object file
test/element_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/element_test.cpp.o
.PHONY : test/element_test.cpp.o

test/element_test.i: test/element_test.cpp.i
.PHONY : test/element_test.i

# target to preprocess a source file
test/element_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/element_test.cpp.i
.PHONY : test/element_test.cpp.i

test/element_test.s: test/element_test.cpp.s
.PHONY : test/element_test.s

# target to generate assembly for a file
test/element_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/element_test.cpp.s
.PHONY : test/element_test.cpp.s

test/event_notifier_test.o: test/event_notifier_test.cpp.o
.PHONY : test/event_notifier_test.o

# target to build an object file
test/event_notifier_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/event_notifier_test.cpp.o
.PHONY : test/event_notifier_test.cpp.o

test/event_notifier_test.i: test/event_notifier_test.cpp.i
.PHONY : test/event_notifier_test.i

# target to preprocess a source file
test/event_notifier_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/event_notifier_test.cpp.i
.PHONY : test/event_notifier_test.cpp.i

test/event_notifier_test.s: test/event_notifier_test.cpp.s
.PHONY : test/event_notifier_test.s

# target to generate assembly for a file
test/event_notifier_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/event_notifier_test.cpp.s
.PHONY : test/event_notifier_test.cpp.s

test/file_data_provider_test.o: test/file_data_provider_test.cpp.o
.PHONY : test/file_data_provider_test.o

# target to build an object file
test/file_data_provider_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/file_data_provider_test.cpp.o
.PHONY : test/file_data_provider_test.cpp.o

test/file_data_provider_test.i: test/file_data_provider_test.cpp.i
.PHONY : test/file_data_provider_test.i

# target to preprocess a source file
test/file_data_provider_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/file_data_provider_test.cpp.i
.PHONY : test/file_data_provider_test.cpp.i

test/file_data_provider_test.s: test/file_data_provider_test.cpp.s
.PHONY : test/file_data_provider_test.s

# target to generate assembly for a file
test/file_data_provider_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/file_data_provider_test.cpp.s
.PHONY : test/file_data_provider_test.cpp.s

test/judge_collector_test.o: test/judge_collector_test.cpp.o
.PHONY : test/judge_collector_test.o

# target to build an object file
test/judge_collector_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/judge_collector_test.cpp.o
.PHONY : test/judge_collector_test.cpp.o

test/judge_collector_test.i: test/judge_collector_test.cpp.i
.PHONY : test/judge_collector_test.i

# target to preprocess a source file
test/judge_collector_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/judge_collector_test.cpp.i
.PHONY : test/judge_collector_test.cpp.i

test/judge_collector_test.s: test/judge_collector_test.cpp.s
.PHONY : test/judge_collector_test.s

# target to generate assembly for a file
test/judge_collector_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/judge_collector_test.cpp.s
.PHONY : test/judge_collector_test.cpp.s

test/move_to_front_test.o: test/move_to_front_test.cpp.o
.PHONY : test/move_to_front_test.o

# target to build an object file
test/move_to_front_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/move_to_front_test.cpp.o
.PHONY : test/move_to_front_test.cpp.o

test/move_to_front_test.i: test/move_to_front_test.cpp.i
.PHONY : test/move_to_front_test.i

# target to preprocess a source file
test/move_to_front_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/move_to_front_test.cpp.i
.PHONY : test/move_to_front_test.cpp.i

test/move_to_front_test.s: test/move_to_front_test.cpp.s
.PHONY : test/move_to_front_test.s

# target to generate assembly for a file
test/move_to_front_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/move_to_front_test.cpp.s
.PHONY : test/move_to_front_test.cpp.s

test/mtf_matrix_test.o: test/mtf_matrix_test.cpp.o
.PHONY : test/mtf_matrix_test.o

# target to build an object file
test/mtf_matrix_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/mtf_matrix_test.cpp.o
.PHONY : test/mtf_matrix_test.cpp.o

test/mtf_matrix_test.i: test/mtf_matrix_test.cpp.i
.PHONY : test/mtf_matrix_test.i

# target to preprocess a source file
test/mtf_matrix_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/mtf_matrix_test.cpp.i
.PHONY : test/mtf_matrix_test.cpp.i

test/mtf_matrix_test.s: test/mtf_matrix_test.cpp.s
.PHONY : test/mtf_matrix_test.s

# target to generate assembly for a file
test/mtf_matrix_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/mtf_matrix_test.cpp.s
.PHONY : test/mtf_matrix_test.cpp.s

test/proccessor_test.o: test/proccessor_test.cpp.o
.PHONY : test/proccessor_test.o

# target to build an object file
test/proccessor_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/proccessor_test.cpp.o
.PHONY : test/proccessor_test.cpp.o

test/proccessor_test.i: test/proccessor_test.cpp.i
.PHONY : test/proccessor_test.i

# target to preprocess a source file
test/proccessor_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/proccessor_test.cpp.i
.PHONY : test/proccessor_test.cpp.i

test/proccessor_test.s: test/proccessor_test.cpp.s
.PHONY : test/proccessor_test.s

# target to generate assembly for a file
test/proccessor_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/proccessor_test.cpp.s
.PHONY : test/proccessor_test.cpp.s

test/tester_test.o: test/tester_test.cpp.o
.PHONY : test/tester_test.o

# target to build an object file
test/tester_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/tester_test.cpp.o
.PHONY : test/tester_test.cpp.o

test/tester_test.i: test/tester_test.cpp.i
.PHONY : test/tester_test.i

# target to preprocess a source file
test/tester_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/tester_test.cpp.i
.PHONY : test/tester_test.cpp.i

test/tester_test.s: test/tester_test.cpp.s
.PHONY : test/tester_test.s

# target to generate assembly for a file
test/tester_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/tester_test.cpp.s
.PHONY : test/tester_test.cpp.s

test/tree_root_test.o: test/tree_root_test.cpp.o
.PHONY : test/tree_root_test.o

# target to build an object file
test/tree_root_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/tree_root_test.cpp.o
.PHONY : test/tree_root_test.cpp.o

test/tree_root_test.i: test/tree_root_test.cpp.i
.PHONY : test/tree_root_test.i

# target to preprocess a source file
test/tree_root_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/tree_root_test.cpp.i
.PHONY : test/tree_root_test.cpp.i

test/tree_root_test.s: test/tree_root_test.cpp.s
.PHONY : test/tree_root_test.s

# target to generate assembly for a file
test/tree_root_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/tree_root_test.cpp.s
.PHONY : test/tree_root_test.cpp.s

test/utils_test.o: test/utils_test.cpp.o
.PHONY : test/utils_test.o

# target to build an object file
test/utils_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/utils_test.cpp.o
.PHONY : test/utils_test.cpp.o

test/utils_test.i: test/utils_test.cpp.i
.PHONY : test/utils_test.i

# target to preprocess a source file
test/utils_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/utils_test.cpp.i
.PHONY : test/utils_test.cpp.i

test/utils_test.s: test/utils_test.cpp.s
.PHONY : test/utils_test.s

# target to generate assembly for a file
test/utils_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/test/utils_test.cpp.s
.PHONY : test/utils_test.cpp.s

tools/judges/deviation_judge.o: tools/judges/deviation_judge.cpp.o
.PHONY : tools/judges/deviation_judge.o

# target to build an object file
tools/judges/deviation_judge.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/deviation_judge.cpp.o
.PHONY : tools/judges/deviation_judge.cpp.o

tools/judges/deviation_judge.i: tools/judges/deviation_judge.cpp.i
.PHONY : tools/judges/deviation_judge.i

# target to preprocess a source file
tools/judges/deviation_judge.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/deviation_judge.cpp.i
.PHONY : tools/judges/deviation_judge.cpp.i

tools/judges/deviation_judge.s: tools/judges/deviation_judge.cpp.s
.PHONY : tools/judges/deviation_judge.s

# target to generate assembly for a file
tools/judges/deviation_judge.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/deviation_judge.cpp.s
.PHONY : tools/judges/deviation_judge.cpp.s

tools/judges/deviation_judge_test.o: tools/judges/deviation_judge_test.cpp.o
.PHONY : tools/judges/deviation_judge_test.o

# target to build an object file
tools/judges/deviation_judge_test.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/deviation_judge_test.cpp.o
.PHONY : tools/judges/deviation_judge_test.cpp.o

tools/judges/deviation_judge_test.i: tools/judges/deviation_judge_test.cpp.i
.PHONY : tools/judges/deviation_judge_test.i

# target to preprocess a source file
tools/judges/deviation_judge_test.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/deviation_judge_test.cpp.i
.PHONY : tools/judges/deviation_judge_test.cpp.i

tools/judges/deviation_judge_test.s: tools/judges/deviation_judge_test.cpp.s
.PHONY : tools/judges/deviation_judge_test.s

# target to generate assembly for a file
tools/judges/deviation_judge_test.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/deviation_judge_test.cpp.s
.PHONY : tools/judges/deviation_judge_test.cpp.s

tools/judges/tester.o: tools/judges/tester.cpp.o
.PHONY : tools/judges/tester.o

# target to build an object file
tools/judges/tester.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/tester.cpp.o
.PHONY : tools/judges/tester.cpp.o

tools/judges/tester.i: tools/judges/tester.cpp.i
.PHONY : tools/judges/tester.i

# target to preprocess a source file
tools/judges/tester.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/tester.cpp.i
.PHONY : tools/judges/tester.cpp.i

tools/judges/tester.s: tools/judges/tester.cpp.s
.PHONY : tools/judges/tester.s

# target to generate assembly for a file
tools/judges/tester.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/judges/tester.cpp.s
.PHONY : tools/judges/tester.cpp.s

tools/processor.o: tools/processor.cpp.o
.PHONY : tools/processor.o

# target to build an object file
tools/processor.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/processor.cpp.o
.PHONY : tools/processor.cpp.o

tools/processor.i: tools/processor.cpp.i
.PHONY : tools/processor.i

# target to preprocess a source file
tools/processor.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/processor.cpp.i
.PHONY : tools/processor.cpp.i

tools/processor.s: tools/processor.cpp.s
.PHONY : tools/processor.s

# target to generate assembly for a file
tools/processor.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/processor.cpp.s
.PHONY : tools/processor.cpp.s

tools/processor_factory.o: tools/processor_factory.cpp.o
.PHONY : tools/processor_factory.o

# target to build an object file
tools/processor_factory.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/processor_factory.cpp.o
.PHONY : tools/processor_factory.cpp.o

tools/processor_factory.i: tools/processor_factory.cpp.i
.PHONY : tools/processor_factory.i

# target to preprocess a source file
tools/processor_factory.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/processor_factory.cpp.i
.PHONY : tools/processor_factory.cpp.i

tools/processor_factory.s: tools/processor_factory.cpp.s
.PHONY : tools/processor_factory.s

# target to generate assembly for a file
tools/processor_factory.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/tools/processor_factory.cpp.s
.PHONY : tools/processor_factory.cpp.s

utils/utils.o: utils/utils.cpp.o
.PHONY : utils/utils.o

# target to build an object file
utils/utils.cpp.o:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/utils/utils.cpp.o
.PHONY : utils/utils.cpp.o

utils/utils.i: utils/utils.cpp.i
.PHONY : utils/utils.i

# target to preprocess a source file
utils/utils.cpp.i:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/utils/utils.cpp.i
.PHONY : utils/utils.cpp.i

utils/utils.s: utils/utils.cpp.s
.PHONY : utils/utils.s

# target to generate assembly for a file
utils/utils.cpp.s:
	$(MAKE) -f CMakeFiles/MTF_TEST.dir/build.make CMakeFiles/MTF_TEST.dir/utils/utils.cpp.s
.PHONY : utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MTF"
	@echo "... MTF_TEST"
	@echo "... MTF_GTEST"
	@echo "... algorithm"
	@echo "... configuration"
	@echo "... data_managment"
	@echo "... event"
	@echo "... exception"
	@echo "... element"
	@echo "... result"
	@echo "... tool"
	@echo "... util"
	@echo "... CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.1.3/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... algorithms/algorithm_container.o"
	@echo "... algorithms/algorithm_container.i"
	@echo "... algorithms/algorithm_container.s"
	@echo "... algorithms/matrix/mtf_matrix.o"
	@echo "... algorithms/matrix/mtf_matrix.i"
	@echo "... algorithms/matrix/mtf_matrix.s"
	@echo "... algorithms/move_to_front/move_to_front.o"
	@echo "... algorithms/move_to_front/move_to_front.i"
	@echo "... algorithms/move_to_front/move_to_front.s"
	@echo "... algorithms/tree/random_tree_root.o"
	@echo "... algorithms/tree/random_tree_root.i"
	@echo "... algorithms/tree/random_tree_root.s"
	@echo "... algorithms/tree/tree_root.o"
	@echo "... algorithms/tree/tree_root.i"
	@echo "... algorithms/tree/tree_root.s"
	@echo "... controller/analysis_runner.o"
	@echo "... controller/analysis_runner.i"
	@echo "... controller/analysis_runner.s"
	@echo "... controller/configuration/configuration.o"
	@echo "... controller/configuration/configuration.i"
	@echo "... controller/configuration/configuration.s"
	@echo "... controller/configuration/objects_builder.o"
	@echo "... controller/configuration/objects_builder.i"
	@echo "... controller/configuration/objects_builder.s"
	@echo "... data_managment/data_output/csv_data_output.o"
	@echo "... data_managment/data_output/csv_data_output.i"
	@echo "... data_managment/data_output/csv_data_output.s"
	@echo "... data_managment/data_output/csv_file_data_output.o"
	@echo "... data_managment/data_output/csv_file_data_output.i"
	@echo "... data_managment/data_output/csv_file_data_output.s"
	@echo "... data_managment/data_output/file_data_output.o"
	@echo "... data_managment/data_output/file_data_output.i"
	@echo "... data_managment/data_output/file_data_output.s"
	@echo "... data_managment/data_provider/file_data_provider.o"
	@echo "... data_managment/data_provider/file_data_provider.i"
	@echo "... data_managment/data_provider/file_data_provider.s"
	@echo "... data_managment/database.o"
	@echo "... data_managment/database.i"
	@echo "... data_managment/database.s"
	@echo "... data_managment/results_collectors/data_collector.o"
	@echo "... data_managment/results_collectors/data_collector.i"
	@echo "... data_managment/results_collectors/data_collector.s"
	@echo "... data_managment/results_collectors/judge_collector.o"
	@echo "... data_managment/results_collectors/judge_collector.i"
	@echo "... data_managment/results_collectors/judge_collector.s"
	@echo "... data_managment/results_collectors/result_collector.o"
	@echo "... data_managment/results_collectors/result_collector.i"
	@echo "... data_managment/results_collectors/result_collector.s"
	@echo "... elements/complex_difference_element.o"
	@echo "... elements/complex_difference_element.i"
	@echo "... elements/complex_difference_element.s"
	@echo "... elements/element.o"
	@echo "... elements/element.i"
	@echo "... elements/element.s"
	@echo "... elements/simple_element.o"
	@echo "... elements/simple_element.i"
	@echo "... elements/simple_element.s"
	@echo "... events/event_notifier.o"
	@echo "... events/event_notifier.i"
	@echo "... events/event_notifier.s"
	@echo "... exceptions/data_provider_exception.o"
	@echo "... exceptions/data_provider_exception.i"
	@echo "... exceptions/data_provider_exception.s"
	@echo "... exceptions/database_exception.o"
	@echo "... exceptions/database_exception.i"
	@echo "... exceptions/database_exception.s"
	@echo "... exceptions/element_already_exists.o"
	@echo "... exceptions/element_already_exists.i"
	@echo "... exceptions/element_already_exists.s"
	@echo "... exceptions/end_of_file_exception.o"
	@echo "... exceptions/end_of_file_exception.i"
	@echo "... exceptions/end_of_file_exception.s"
	@echo "... exceptions/file_path_exception.o"
	@echo "... exceptions/file_path_exception.i"
	@echo "... exceptions/file_path_exception.s"
	@echo "... exceptions/invalid_index_exception.o"
	@echo "... exceptions/invalid_index_exception.i"
	@echo "... exceptions/invalid_index_exception.s"
	@echo "... exceptions/invalid_name_exception.o"
	@echo "... exceptions/invalid_name_exception.i"
	@echo "... exceptions/invalid_name_exception.s"
	@echo "... exceptions/non_existing_element.o"
	@echo "... exceptions/non_existing_element.i"
	@echo "... exceptions/non_existing_element.s"
	@echo "... gtest/analysis_runner_test.o"
	@echo "... gtest/analysis_runner_test.i"
	@echo "... gtest/analysis_runner_test.s"
	@echo "... gtest/gtest_main.o"
	@echo "... gtest/gtest_main.i"
	@echo "... gtest/gtest_main.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_test.o"
	@echo "... main_test.i"
	@echo "... main_test.s"
	@echo "... results/overall_result.o"
	@echo "... results/overall_result.i"
	@echo "... results/overall_result.s"
	@echo "... results/result.o"
	@echo "... results/result.i"
	@echo "... results/result.s"
	@echo "... test/data_collector_test.o"
	@echo "... test/data_collector_test.i"
	@echo "... test/data_collector_test.s"
	@echo "... test/database_test.o"
	@echo "... test/database_test.i"
	@echo "... test/database_test.s"
	@echo "... test/element_test.o"
	@echo "... test/element_test.i"
	@echo "... test/element_test.s"
	@echo "... test/event_notifier_test.o"
	@echo "... test/event_notifier_test.i"
	@echo "... test/event_notifier_test.s"
	@echo "... test/file_data_provider_test.o"
	@echo "... test/file_data_provider_test.i"
	@echo "... test/file_data_provider_test.s"
	@echo "... test/judge_collector_test.o"
	@echo "... test/judge_collector_test.i"
	@echo "... test/judge_collector_test.s"
	@echo "... test/move_to_front_test.o"
	@echo "... test/move_to_front_test.i"
	@echo "... test/move_to_front_test.s"
	@echo "... test/mtf_matrix_test.o"
	@echo "... test/mtf_matrix_test.i"
	@echo "... test/mtf_matrix_test.s"
	@echo "... test/proccessor_test.o"
	@echo "... test/proccessor_test.i"
	@echo "... test/proccessor_test.s"
	@echo "... test/tester_test.o"
	@echo "... test/tester_test.i"
	@echo "... test/tester_test.s"
	@echo "... test/tree_root_test.o"
	@echo "... test/tree_root_test.i"
	@echo "... test/tree_root_test.s"
	@echo "... test/utils_test.o"
	@echo "... test/utils_test.i"
	@echo "... test/utils_test.s"
	@echo "... tools/judges/deviation_judge.o"
	@echo "... tools/judges/deviation_judge.i"
	@echo "... tools/judges/deviation_judge.s"
	@echo "... tools/judges/deviation_judge_test.o"
	@echo "... tools/judges/deviation_judge_test.i"
	@echo "... tools/judges/deviation_judge_test.s"
	@echo "... tools/judges/tester.o"
	@echo "... tools/judges/tester.i"
	@echo "... tools/judges/tester.s"
	@echo "... tools/processor.o"
	@echo "... tools/processor.i"
	@echo "... tools/processor.s"
	@echo "... tools/processor_factory.o"
	@echo "... tools/processor_factory.i"
	@echo "... tools/processor_factory.s"
	@echo "... utils/utils.o"
	@echo "... utils/utils.i"
	@echo "... utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

